hydra:
  searchpath:
    - pkg://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_
    
data:
  train_files: /root/data/geo3k/train.parquet
  val_files: /root/data/geo3k/test.parquet
  train_batch_size: 128
  max_prompt_length: 1024
  max_response_length: 4096
  filter_overlong_prompts: True
  truncation: 'error'
  image_key: images
actor_rollout_ref:
  model:
    path: /root/models/Qwen3-VL-4B-Instruct
    use_remove_padding: True
    lora_rank: 64
    lora_alpha: 64
    target_modules: all-linear
    exclude_modules: '.*visual.*'
    enable_gradient_checkpointing: True
    enable_activation_offload: False
    use_shm: True
    use_fused_kernels: True
  actor:
    optim:
      lr: 1e-5
    ppo_mini_batch_size: 32
    use_dynamic_bsz: true
    ppo_max_token_len_per_gpu: 16384
    use_kl_loss: True
    kl_loss_coef: 0.01
    kl_loss_type: low_var_kl
    clip_ratio: 0.2
    clip_ratio_low: 0.2
    clip_ratio_high: 0.2
    strategy: "fsdp2"
    ulysses_sequence_parallel_size: 1
    fsdp_config:
      model_dtype: bfloat16
      param_offload: False
      optimizer_offload: False
  rollout:
    log_prob_use_dynamic_bsz: true
    log_prob_max_token_len_per_gpu: 16384
    tensor_model_parallel_size: 1
    name: vllm
    layered_summon: False
    load_format: "safetensors"
    gpu_memory_utilization: 0.5
    enable_chunked_prefill: True
    enforce_eager: False
    free_cache_engine: False
    n: 5
    temperature: 0.7
    max_num_seqs: 256
    max_model_len: 4096
    max_num_batched_tokens: 8192
    val_kwargs:
      n: 8
      do_sample: False
      temperature: 0.7
  ref:
    log_prob_use_dynamic_bsz: true
    log_prob_max_token_len_per_gpu: 16384
    fsdp_config:
      model_dtype: bfloat16
      param_offload: False
algorithm:
  adv_estimator: grpo
  use_kl_in_reward: False
trainer:
  log_val_generations: 5
  rollout_data_dir: "outputs/rollout_data"
  validation_data_dir: "outputs/validation_data"
  critic_warmup: 0
  logger: ["console","wandb"]
  project_name: 'qwen3_vl_geo3k'
  experiment_name: 'qwen3_vl_grpo'
  n_gpus_per_node: 1
  nnodes: 1
  save_freq: 10
  test_freq: 10
  val_before_train: True
  total_epochs: 7
  resume_mode: "disable"